### ISSUE TITLE
Using non-simulated data?

### ISSUE THREAD

**Issue by DeusCap** [sophiagu/RLF#1]
Hi there!
Just found your paper today and loved the ideas behind it. Admittedly though I don't have a great background/understanding in DRL. 

I was wondering how or what the lift would be to transform some of the env's to take non-simulated data.

Thanks!

**Comment by sophiagu** [comment]
Apparently I don't monitor my github and my repos closely and I only notice your question now...sorry!
idk if it will still help, but here are my quick thoughts:

One big problem of reinforcement learning is that it needs a lot of reward signals to be able to "learn". This work (to some degree) helps to mitigate that problem by limiting the policy search space, and when given a similar amount of data it can converge much faster.
But is it good enough for real data? For simulation, I could just generate tons of data myself, but in reality, how much clean, usable data you can obtain? I think this is a fair assumption that the earliest market data you may be able to access is within 100 years, say you have one usable data point per trading day, then it's like 25k in total, not too bad. But then you have to worry about regime shifts and you don't want to use dated data as they may only hurt your model, so you end up with only about 1k data points in the past 5 years, that's far from enough for training anything plausible! One idea is that this may work for HFT, but those high frequency data are super noisy, so I don't have a good take on your question tbh, except maybe someone really try it out (and lmk!)

**Comment by sophiagu** [comment]
Apparently I don't monitor my github and my repos closely and I only notice your question now...sorry!
idk if it will still help, but here are my quick thoughts:

One big problem of reinforcement learning is that it needs a lot of reward signals to be able to "learn". This work (to some degree) helps to mitigate that problem by limiting the policy search space, and when given a similar amount of data it can converge much faster.
But is it good enough for real data? For simulation, I could just generate tons of data myself, but in reality, how much clean, usable data you can obtain? I think this is a fair assumption that the earliest market data you may be able to access is within 100 years, say you have one usable data point per trading day, then it's like 25k in total, not too bad. But then you have to worry about regime shifts and you don't want to use dated data as they may only hurt your model, so you end up with only about 1k data points in the past 5 years, that's far from enough for training anything plausible! One idea is that this may work for HFT, but those high frequency data are super noisy, so I don't have a good take on your question tbh, except maybe someone really try it out (and lmk!)

**Comment by sophiagu** [comment]
Apparently I don't monitor my github and my repos closely and I only notice your question now...sorry!
idk if it will still help, but here are my quick thoughts:

One big problem of reinforcement learning is that it needs a lot of reward signals to be able to "learn". This work (to some degree) helps to mitigate that problem by limiting the policy search space, and when given a similar amount of data it can converge much faster.

But is it good enough for real data? For simulation, I could just generate tons of data myself, but in reality, how much clean, usable data you can obtain? I think this is a fair assumption that the earliest market data you may be able to access is within 100 years, say you have one usable data point per trading day, then it's like 25k in total, not too bad. But then you have to worry about regime shifts and you don't want to use dated data as they may only hurt your model, so you end up with only about 1k data points in the past 5 years, that's far from enough for training anything plausible!

One idea is that this may work for HFT, but those high frequency data are super noisy, so I don't have a good answer to your question tbh. There were people who tried using synthetic data (I cannot exactly recall their work) with parameters learned from real data, and they showed the performance still surpassed the traditional methods. Another idea may be training on synthetic data first and then finetune the model on empirical data.
